# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 280)
        Dialog.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 260, 111, 17))
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 384, 249))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: none;\n"
"color: rgb(85, 87, 83);\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sept = QtWidgets.QPushButton(self.widget)
        self.sept.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.sept.setObjectName("sept")
        self.verticalLayout.addWidget(self.sept)
        self.quatre = QtWidgets.QPushButton(self.widget)
        self.quatre.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.quatre.setObjectName("quatre")
        self.verticalLayout.addWidget(self.quatre)
        self.un = QtWidgets.QPushButton(self.widget)
        self.un.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.un.setObjectName("un")
        self.verticalLayout.addWidget(self.un)
        self.effacer = QtWidgets.QPushButton(self.widget)
        self.effacer.setStyleSheet("background-color: rgb(245, 121, 0);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.effacer.setObjectName("effacer")
        self.verticalLayout.addWidget(self.effacer)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.huit = QtWidgets.QPushButton(self.widget)
        self.huit.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.huit.setObjectName("huit")
        self.verticalLayout_2.addWidget(self.huit)
        self.cinq = QtWidgets.QPushButton(self.widget)
        self.cinq.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.cinq.setObjectName("cinq")
        self.verticalLayout_2.addWidget(self.cinq)
        self.deux = QtWidgets.QPushButton(self.widget)
        self.deux.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.deux.setObjectName("deux")
        self.verticalLayout_2.addWidget(self.deux)
        self.zero = QtWidgets.QPushButton(self.widget)
        self.zero.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.zero.setObjectName("zero")
        self.verticalLayout_2.addWidget(self.zero)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.neuf = QtWidgets.QPushButton(self.widget)
        self.neuf.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.neuf.setObjectName("neuf")
        self.verticalLayout_3.addWidget(self.neuf)
        self.six = QtWidgets.QPushButton(self.widget)
        self.six.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.six.setObjectName("six")
        self.verticalLayout_3.addWidget(self.six)
        self.trois = QtWidgets.QPushButton(self.widget)
        self.trois.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.trois.setObjectName("trois")
        self.verticalLayout_3.addWidget(self.trois)
        self.entrer = QtWidgets.QPushButton(self.widget)
        self.entrer.setStyleSheet("background-color: rgb(245, 121, 0);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.entrer.setObjectName("entrer")
        self.verticalLayout_3.addWidget(self.entrer)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.division = QtWidgets.QPushButton(self.widget)
        self.division.setStyleSheet("background-color: rgb(252, 175, 62);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.division.setObjectName("division")
        self.verticalLayout_4.addWidget(self.division)
        self.multiplication = QtWidgets.QPushButton(self.widget)
        self.multiplication.setStyleSheet("background-color: rgb(252, 175, 62);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.multiplication.setObjectName("multiplication")
        self.verticalLayout_4.addWidget(self.multiplication)
        self.soustraction = QtWidgets.QPushButton(self.widget)
        self.soustraction.setStyleSheet("background-color: rgb(252, 175, 62);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.soustraction.setObjectName("soustraction")
        self.verticalLayout_4.addWidget(self.soustraction)
        self.addition = QtWidgets.QPushButton(self.widget)
        self.addition.setStyleSheet("background-color: rgb(252, 175, 62);\n"
"border: none;\n"
"color: white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;\n"
"")
        self.addition.setObjectName("addition")
        self.verticalLayout_4.addWidget(self.addition)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculatrice"))
        self.label.setText(_translate("Dialog", "Made by haroun"))
        self.sept.setText(_translate("Dialog", "7"))
        self.quatre.setText(_translate("Dialog", "4"))
        self.un.setText(_translate("Dialog", "1"))
        self.effacer.setText(_translate("Dialog", "C"))
        self.huit.setText(_translate("Dialog", "8"))
        self.cinq.setText(_translate("Dialog", "5"))
        self.deux.setText(_translate("Dialog", "2"))
        self.zero.setText(_translate("Dialog", "0"))
        self.neuf.setText(_translate("Dialog", "9"))
        self.six.setText(_translate("Dialog", "6"))
        self.trois.setText(_translate("Dialog", "3"))
        self.entrer.setText(_translate("Dialog", "="))
        self.division.setText(_translate("Dialog", "/"))
        self.multiplication.setText(_translate("Dialog", "*"))
        self.soustraction.setText(_translate("Dialog", "-"))
        self.addition.setText(_translate("Dialog", "+"))
